DROP SCHEMA IF EXISTS Cpf;
CREATE SCHEMA IF NOT EXISTS Cpf;

CREATE TABLE Cpf.cpfList (
  cpf BIGINT PRIMARY KEY,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO
  Cpf.cpfList (cpf)
VALUES
  (64852893055),
  (64852893056);
  